require 'ankusa/extensions'
require 'ankusa/classifier'
require 'ankusa/naive_bayes'
require 'ankusa/kl_divergence'
require 'ankusa/hasher'
require 'ankusa/memory_storage'
require 'ankusa/hbase_storage'
